apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  5432: "tmate/session:2200"
  # 5432: "kubemacs/postgres:5432"
  # 10350: "kubemacs/kubemacs-tilt:10350"
