apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  2200: "ii/services:2200"
  5432: "ii/postgres:5432"
  10350: "ii/kubemacs-tilt:10350"
---
#https://kubernetes.github.io/ingress-nginx/examples/rewrite/
---
---
---
---
# https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#http-via-nginx
# kubectl delete secret basic-auth
# kubectl create secret generic basic-auth --from-literal=auth=$(htpasswd -n ii)
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: pgadmin-browser-ingress
#   annotations:
#     # nginx.ingress.kubernetes.io/app-root: /pgadmin
#     nginx.ingress.kubernetes.io/rewrite-target: /pgadmin/browser/$2
#     nginx.ingress.kubernetes.io/configuration-snippet: |
#       proxy_set_header X-Script-Name "/pgadmin";
#       proxy_set_header X-Scheme $scheme;
#       proxy_set_header Host $host;
#     nginx.ingress.kubernetes.io/auth-type: basic
#     nginx.ingress.kubernetes.io/auth-secret: basic-auth
#     nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - PgAdmin'
#   # annotations:
#   #   nginx.ingress.kubernetes.io/app-root: /
#   # annotations:
#   #   nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       # - path: /pgadmin
#       - path: /pgadmin/browser(/|$)(.*)
#         backend:
#           serviceName: pgadmin
#           servicePort: 80
