apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: auditlogger
spec:
  policy:
    level: Metadata
    stages:
    - ResponseComplete
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      #url: "http://apisnoop-auditlogger.kube-system.svc.cluster.local:9900/events"
      # svc cluster ip of apisnoop-auditlogger
      url: "http://10.96.96.96:9900/events"
