apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisnoop-auditlogger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.apisnoop.auditlogger: apisnoop-auditlogger
  template:
    metadata:
      labels:
        io.apisnoop.auditlogger: apisnoop-auditlogger
    spec:
      containers:
        - name: apisnoop-auditlogger
          image: "gcr.io/k8s-staging-apisnoop/auditlogger:v20200211-0.9.34-1-g24cf96f"
          #command:
          #  - "sleep"
          #args: 
          #  - "10000000"
          ports:
            - containerPort: 9900
