apiVersion: v1
kind: Service
metadata:
  name: apisnoop-auditlogger
spec:
  ports:
    - port: 9900
      targetPort: 9900
  selector:
    io.apisnoop.auditlogger: apisnoop-auditlogger
  clusterIP: 10.96.96.96
  type: ClusterIP
